service: shoppingListService # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
 
custom:
  client:
    bucketName: my-shopping-list-demo
    distributionFolder: ../website/build

plugins:
  - serverless-finch    
