service: shoppingListService # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10

functions:
  getList:
    handler: src/getList.getList
    events:
      - http:
          path: list
          method: get
          cors: true
  putItem:
    handler: src/putItem.putItem
    events:
      - http:
          path: list
          method: put
          cors: true

custom:
  client:
    bucketName: my-shopping-list-demo
    distributionFolder: ../website/build

plugins:
  - serverless-finch    
